@playlist_id = someplaylistid
@spotify_track_uri = spotify:track:sometrackid

POST http://localhost:3000/api/spotify/save/{{playlist_id}}
Content-Type: application/json

{
  "token_type": "Bearer",
  "access_token": "{{spotifyAccessToken}}",
  "uris": ["{{spotify_track_uri}}"]
}

##############################################################################################

@cursor = 2022-08-17T00:37:32.561Z
@take = 12
GET http://localhost:3000/api/tracks?cursor={{cursor}}&take={{take}}
